### PR TITLE
Adjust VAEncMiscParameterQuantization structure to be align with VAEn…

### PR DESCRIPTION
**Pull request by XinfengZhang**
…cMiscParameterBuffer

Fixes:#265

Signed-off-by: intel <carl.zhang@intel.com>

### CODE REVIEW

**Comment by XinfengZhang** [comment]
@lizhong1008 yes, it will in 2.5 if there are no other concern, I am wondering whether it will break ABI

**Comment by XinfengZhang** [comment]
mark it with "help wanted" , this PR potentially will break backward compatible. but it is a fix. previous implementation will have some issue when user use it like #265 , please help to review, if no other concern , I will merge it in 2 weeks.

**Comment by fulinjie** [comment]
Ping?

**Comment by XinfengZhang** [comment]
@Erick555 hi , is libabigail will report issues with this changes? if freedesktop-sdk accept it?

**Comment by Erick555** [comment]
@XinfengZhang I don't know. We're in preparation for a new major release and we won't check ABI until it's finished. At the same time current stable release is more or less frozen, perhaps we won't update libva there anymore. That means we won't complain regardless if this trigger libabigail warning or not :smiley:.

**Pull request merged**
