### PR TITLE
README: drop mailing list, IRC and Slack

### PR DESCRIPTION
**Pull request by evelikov**
All three are effectively dead. In particular:
 - the ML has disappeared with the update to HyperKitty
 - Freenode has imploded - channel has not moved to Libera/OFTC
 - Slack is a ghost town - last two maintainers are not even on it

@XinfengZhang @dvrogozh @xhaihao @uartie

### CODE REVIEW

**Review by dvrogozh — APPROVED** [review]
Mailing list and IRC are dead links.

Slack might still be there. But saying for myself, I am not using it. @xhaihao @uartie - can you weigh on whether Slack still represent a meaningful channel for libva? /I think answer is no, but would like to double check/

**Comment by uartie** [comment]
> Mailing list and IRC are dead links.
> 
> Slack might still be there. But saying for myself, I am not using it. @xhaihao @uartie - can you weigh on whether Slack still represent a meaningful channel for libva? /I think answer is no, but would like to double check/

I don't think anyone uses the slack channel(s) anymore, either.

**Review by uartie — APPROVED** [review]
Yes, https://github.com/intel/media-driver maintainers are now the primary maintainers of libva, too.  Github issues seems to be the best way to interact with them.

**Comment by evelikov-work** [comment]
@uartie @dvrogozh can you provide some input to https://github.com/intel/libva/issues/622?

libva is a community project where various people, companies and vendors have drivers for. At the same time, having a selected few Intel employees as maintainers seems sub-optimal. At first there's no public list who they are, as outlined in the issue above - even when they've approved PRs, those don't get merged for months. Last but not least, if any of those people decide to change positions or leave Intel then everyone will suffer.

**Comment by evelikov** [comment]
@uartie @dvrogozh can you provide some input to https://github.com/intel/libva/issues/622?

libva is a community project where various people, companies and vendors have drivers for. At the same time, having a selected few Intel employees as maintainers seems sub-optimal. At first there's no public list who they are, as outlined in the issue above - even when they've approved PRs, those don't get merged for months. Last but not least, if any of those people decide to change positions or leave Intel then everyone will suffer.

**Pull request merged**
