### PR TITLE
add qp adjustment control for HEVC CQP mode

### PR DESCRIPTION
**Pull request by XinfengZhang**
Signed-off-by: XinfengZhang <carl.zhang@intel.com>

### CODE REVIEW

**Comment by fhvwy** [comment]
Can you explain more about exactly what this field is intended to do?  It doesn't look like it should be in `seq_fields` because there is no sequence parameter set field of that name.

**Comment by XinfengZhang** [comment]
@fhvwy sorry for late response. it's CNY. this parameter is only for CQP,  in motion estimation stage, we can get the complexities of the picture, with these data, we can set different QP for different areas  to get better quality and higher compression rate.  it is not exist in HEVC spec. just an enhancement for HEVC CQP

**Comment by fhvwy** [comment]
@XinfengZhang  I'm pretty sure it shouldn't be in the sequence parameter structure, then.  Instead it sounds like it should be a rate control option, though one that applies when bitrate control is not being used (like CRF of libx264).  The quantisation parameter really should be constant when in Constant Quantisation Parameter mode (and H.265 may enforce this because `cu_qp_delta_enabled_flag` need not be set), so maybe you want a new rate control mode (a new `VA_RC_*` value) for this?  Perhaps some sort of constant-quality mode, with this option as one of its parameters?

**Comment by XinfengZhang** [comment]
@fhvwy cu_qp_delta_enabled_flag should just control the delta Qp for the CU inside CTB, right? I am not sure whether it also present the Qp difference of CTB. this feature is for CQP, I wonder whether a new BRC method is suitable

**Comment by fhvwy** [comment]
The change in this form isn't backward compatible, because a v2.1 driver supporting MB RC in VBR mode will now appear to support MB RC in CQP mode when it doesn't.  It probably needs to be a new flag if you do this.

Wrt cu_qp_delta_enabled_flag in H.265, the (luma) QP can't be changed at all inside a slice if it isn't set.  Does your scheme want to modify the QP?  If it does then it definitely can't be used with CQP mode, and a new mode would be required instead.

**Comment by XinfengZhang** [comment]
just like @fhvwy  mentioned, no strong reason for this change

**Pull request closed without merging**
