### PR TITLE
build documentation with meson

### PR DESCRIPTION
**Pull request by ceyusa**
This pull request aims for building the documentation with meson.

In order to achieve it, it is required to move from using environment variables for passing Doxygen configuration, to the configuration template generation. In the case of autotools, sed is used.

### CODE REVIEW

**Comment by xhaihao** [comment]
It always re-generate the docs when running ninja even if I don't change any files.

**Comment by ceyusa** [comment]
> It always re-generate the docs when running ninja even if I don't change any files.

Fixed

**Comment by xhaihao** [comment]
@ceyusa 'make distclean' is broken now, the regression is caused by https://github.com/intel/libva/pull/172/commits/f17486f65648715119ba020ad6bb0e6775bd76af 

```
Makefile:496: ../drm/.deps/va_drm_utils.Plo: No such file or directory
make[2]: *** No rule to make target '../drm/.deps/va_drm_utils.Plo'.  Stop.
```

**Comment by ceyusa** [comment]
oops! true! subdir-objects wasn't a good idea

```
--- a/configure.ac
+++ b/configure.ac
@@ -90,7 +90,7 @@ AC_INIT([libva],
 
 AC_CONFIG_SRCDIR([Makefile.am])
 AC_CONFIG_MACRO_DIR([m4])
-AM_INIT_AUTOMAKE([dist-bzip2 subdir-objects -Wno-portability])
+AM_INIT_AUTOMAKE([dist-bzip2 -Wno-portability])
 
 AC_CONFIG_HEADERS([config.h])
 m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES([yes])])
```

Does that work for you? 
Should I make a pull request for it?

**Comment by xhaihao** [comment]
yes, it works without subdir-objects, please submit a pull request. thanks

**Comment by xhaihao** [comment]
@ceyusa I pushed your patch

**Pull request merged**
