### PR TITLE
Add VVC decode LibVA interface.

### PR DESCRIPTION
**Pull request by ChunjuanLiu**

### CODE REVIEW

**Comment by oscarbg** [comment]
@ChunjuanLiu any related ffmpeg branch or patches with libva VCC decode support? Also libva-utils vcc support (vainfo for ex.) thanks..

**Comment by feiwan1** [comment]
Hi @oscarbg, ffmpeg vaapi vvc decoder PR https://github.com/intel-media-ci/ffmpeg/pull/714.

**Review by XinfengZhang — APPROVED** [review]

**Comment by XinfengZhang** [comment]
please squash the commits together and rebase it. thanks

**Review by XinfengZhang — APPROVED** [review]

**Comment by XinfengZhang** [comment]
VA_RC_MB represent microblock based rate control
    but rate control implementation should be transparent to application.

    application does not care whether the BRC is microblock based or sub block based
    or frame based. it just care the quality and compression rate.

**Comment by widgetii** [comment]
Is there any hardware to tests on the market?

**Comment by XinfengZhang** [comment]
> Is there any hardware to tests on the market?

intel new platform LNL will support it

**Pull request merged**
