### PR TITLE
High Dynamic Range Tone Mapping: Add a new filter for input metadata …

### PR DESCRIPTION
**Pull request by FurongZhang**
…and some comments.

Signed-off-by: furongzh <furong.zhang@intel.com>

### CODE REVIEW

**Comment by FurongZhang** [comment]
@vvkalinin24 Thank you so much.

**Comment by dmitryermilov** [comment]
It looks good

**Comment by FurongZhang** [comment]
@vvkalinin24 Is it possible for you to help to merge into master? Thanks a lot in advance!

**Comment by vvkalinin24** [comment]
> @vvkalinin24 Is it possible for you to help to merge into master? Thanks a lot in advance!

@xhaihao Can you please review this pull request and help to merge it

**Pull request merged**
