### PR TITLE
ci: fix freebsd build by switching to vmactions/freebsd-vm@v0.1.5

### PR DESCRIPTION
**Pull request by dvrogozh**
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

### CODE REVIEW

**Comment by dvrogozh** [comment]
@jbeich : any suggestions why this fails? But it seems to me this is an issue with the host (which is macos) or action itself. So, I will file an issue to them.

**Review by XinfengZhang — APPROVED** [review]

**Comment by dvrogozh** [comment]
I think I understood what's wrong. We were using "macos-latest" for the host which previously was 10.15.7. Now systems start getting update to 11.6.1 which miss `vboxmanage`. I s/macos-latest/macos-10.15/ and ci started to pass.

**Comment by dvrogozh** [comment]
This is change solely in freebsd.yml, ubuntu workloads won't start. Can be merged.

**Comment by dvrogozh** [comment]
fyi, I submitted [#38](https://github.com/vmactions/freebsd-vm/issues/38) to note behavior on macos-latest runners.

**Pull request merged**
