### PR TITLE
unify the coding style in libva

### PR DESCRIPTION
**Pull request by xhaihao**
Please run autogen.sh to install the pre-commit hook after applying the patch series

### CODE REVIEW

**Comment by xhaihao** [comment]
@seanvk No, I am not going to have a new coding style in libva as the script to handle the coding style in libva was added a few years ago. I only updated the script with a change, ran the script and added pre-commit hook to ensure the commit follows the coding style.

**Comment by seanvk** [comment]
Okay, thanks for addressing my comments @xhaihao

**Comment by chivakker** [comment]
This needs a rebase

**Comment by uartie** [comment]
Inactive and out of date.  Please resubmit if this is still needed.

**Pull request closed without merging**
