### PR TITLE
add fourcc code for P012 format

### PR DESCRIPTION
**Pull request by sunxinpeng**
Signed-off-by: Xinpeng Sun <xinpeng.sun@intel.com>

### CODE REVIEW

**Comment by sunxinpeng** [comment]
@XinfengZhang Hi Carl, could you help to review this patch for adding P012 fourcc?

**Comment by XinfengZhang** [comment]
LGTM, but also need https://github.com/intel/media-driver correlated changes

**Comment by wangyan42164** [comment]
@sunxinpeng Could you please one test case for this. I can change media driver and try it. Thanks.

**Comment by feiwan1** [comment]
Hi @wangyan42164 , I have tested with your pull request https://github.com/intel/media-driver/pull/921 by using ffmpeg, it looks good to me. Thanks

**Pull request merged**
