### PR TITLE
Add definition for input/output surface flag

### PR DESCRIPTION
**Pull request by Jister**

### CODE REVIEW

**Comment by XinfengZhang** [comment]
changes  of input_surface_flag & output_surface_flag  is not backward compatible, it move the "protected" flag from lowest bit to highest bit.   I wonder whether there are user is using the "protected" surface , if no real usage, I am ok to change it. but if there are usage, we cant change it. @xhaihao @fhvwy @chivakker  , could you help to confirm whether there are usage, from i965, FFmpeg, gstreamer view?

**Comment by XinfengZhang** [comment]
if no other concern, I will merge it in 1 week , thanks

**Comment by XinfengZhang** [comment]
@fhvwy @ceyusa  do you have concern about it?

**Comment by ceyusa** [comment]
There is no use of the protection bit in gstreamer-vaapi. Lgtm :)

**Pull request merged**
