### PR TITLE
Enable github actions

### PR DESCRIPTION
**Pull request by dvrogozh**
Recently Travis CI has significant latency before jobs are actually started. My estimation is around 24h. This significantly delays in time reaction on the PRs and delays merges. For example, we have issue to verify that #363 which introduces BSD support buils correctly. This change is an attempt to switch to github actions which seem to start almost instantly. This also verifies that BSD changes build correctly.

Actions:
* https://github.com/dvrogozh/libva/actions/runs/311038053 - freebsd
* https://github.com/dvrogozh/libva/actions/runs/311038049 - ubuntu

### CODE REVIEW

**Review by onabiull — APPROVED** [review]
I like it 👍

**Comment by XinfengZhang** [comment]
LGTM

**Review by XinfengZhang — APPROVED** [review]

**Comment by XinfengZhang** [comment]
hi @dvrogozh , it is a draft pr,  do you have any concern? or just a test purpose?

**Comment by dvrogozh** [comment]
> hi @dvrogozh , it is a draft pr, do you have any concern? or just a test purpose?

No concerns from my side. I just thought to gather feedback. Promoted to full PR now.

**Pull request merged**
