### PR TITLE
NULL check before calling strncmp()

### PR DESCRIPTION
**Pull request by Dylan-debug**
NULL check before calling strncmp()

Signed-off-by: caij jianxing.cai@intel.com

### CODE REVIEW

**Review by XinfengZhang — APPROVED** [review]

**Comment by evelikov** [comment]
Oops introduced with https://github.com/intel/libva/pull/688 @sivileri

**Comment by evelikov** [comment]
@Dylan-debug some unrelated white-space got in - see the failing pipeline. While there, please tweak the commit message - say `drm: NULL check before calling strncmp()`

**Comment by sivileri** [comment]
Thanks for fixing this one! looks good to me.

**Review by dvrogozh — APPROVED** [review]
yes, we've missed that. Approved.

**Pull request merged**
