### PR TITLE
disable travis build

### PR DESCRIPTION
**Pull request by XinfengZhang**
already enable github actions

Signed-off-by: Carl Zhang <carl.zhang@intel.com>

### CODE REVIEW

**Comment by dvrogozh** [comment]
It seems Coverity scan is the only thing which is available in travis and is missing in our github actions setup. Everything else, i.e. ubuntu and freebsd builds, are there in github actions now. 

Thus the question is: do we need Coverity scan for the libva? Badge on the top page seems to be broken (goes to https://scan.coverity.com/projects/intel-libva which gives 404 error to me). So, I am even not sure if the scan is still alive. If it is not, yep, let's disable travis.

**Comment by XinfengZhang** [comment]
the coverity scan should base on branch https://github.com/intel/libva/tree/coverity_scan, not master, we did not update the branch long time

**Review by dvrogozh — APPROVED** [review]

**Comment by dvrogozh** [comment]
@XinfengZhang : I am going to merge this in.

**Comment by XinfengZhang** [comment]
sure, no problem.

**Pull request merged**
